--< example

return {
	
	Common = {
		Color3 = Color3.fromRGB(197, 200, 200),
		["%"] = 80
	},
	
	Uncommon = {
		Color3 = Color3.fromRGB(194, 255, 183),
		["%"] = 70
	},
	
	Rare = {
		Color3 = Color3.fromRGB(105, 180, 250),
		["%"] = 50
	},
	
	
	Epic = {
		Color3 = Color3.fromRGB(174, 80, 250),
		["%"] = 30
	},
	
	Legendary = {
		Color3 = Color3.fromRGB(243, 228, 121),
		["%"] = 15
	},
	
	Mythic = {
		Color3 = Color3.fromRGB(255, 0, 0),
		["%"] = 5
	},
	
	
	Limited = {
		Color3 = Color3.fromRGB(191, 51, 35),
		["%"] = 0
	},
	
}