return {
	Likes = 0,
	Cash = 0,
	Rebirths = 0,
	
	HitPower = 0,
	
	RunSpeed = 0,	
	
	Inventory = {
		Brainrots =  {
			
		},
		
		Weights = {
			
		},
	},
	
	BrainrotIndex = {
		
		-- ["BrainrotName_BrainrotType"] = true,
		
	},
	
	
	Plot = {
		Floor1 = {
			["Slot1"] = "None", 
			["Slot2"] = "None",
			["Slot3"] = "None",
			["Slot4"] = "None",
			["Slot5"] = "None",
			["Slot6"] = "None",
			["Slot7"] = "None",
			["Slot8"] = "None",
			["Slot9"] = "None",
			["Slot10"] = "None",
		},
		
		-- other floors will be added when the player unlocks them
		--[[
		
			Floor2 = {
			
			-- slots will be added when the player unlock them
			["Slot1"] = "None", -- here will be the name of the brainrot
			["Slot2"] = "None",
			...
			["Slot9"] = "None",
			["Slot10"] = "None",
			},
		
		]]
	}
}